dist: bionic
sudo: required

branches:
  only:
  - master
  - develop

language: php

php:
  # Test oldest and newest maintained versions.
  - '7.4'
  - '8.0'

env:
  # Test oldest and newest maintained versions.
  - PGVERSION=9.6
  - PGVERSION=13

before_install:
  # Output info for debugging.
  - php -r "echo phpinfo();"

  # Update the package list.
  - sudo apt-get update

  # Install Apache.
  # From https://docs.travis-ci.com/user/languages/php
  # Currently Travis CI does not support mod_php for apache, but you can
  # configure php-fpm for your integration tests.
  - sudo apt-get install apache2
  # Install mod_fastcgi which is no longer available in Ubuntu repositories.
  - wget http://mirrors.kernel.org/ubuntu/pool/multiverse/liba/libapache-mod-fastcgi/libapache2-mod-fastcgi_2.4.7~0910052141-1.2_amd64.deb
  - sudo dpkg -i libapache2-mod-fastcgi_2.4.7~0910052141-1.2_amd64.deb
  # enable php-fpm
  - sudo a2enmod rewrite actions fastcgi alias
  - echo "cgi.fix_pathinfo = 1" >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini
  - sudo sed -i -e "s,www-data,travis,g" /etc/apache2/envvars
  - sudo chown -R travis:travis /var/lib/apache2/fastcgi
  - ~/.phpenv/versions/$(phpenv version-name)/sbin/php-fpm
  # configure apache virtual hosts
  - sudo cp -f .travis/travis-ci-apache /etc/apache2/sites-available/000-default.conf
  - sudo sed -e "s?%TRAVIS_BUILD_DIR%?$(pwd)?g" --in-place /etc/apache2/sites-available/000-default.conf
  - sudo service apache2 restart

  # Reinstall PostgreSQL - see https://github.com/travis-ci/travis-ci/issues/7048#issuecomment-267731971
  - sudo apt-get autoremove postgis*
  - sudo apt-get autoremove postgresql*
  - sudo apt-get install postgresql-${PGVERSION}-postgis-3 postgresql-contrib-${PGVERSION}
  - PGDATA=/var/ramfs/postgresql/${PGVERSION}/main
  - PGBIN=/usr/lib/postgresql/${PGVERSION}/bin
  - sudo mkdir -p $PGDATA
  - sudo chown -R postgres:postgres /var/ramfs/postgresql
  - sudo -u postgres ${PGBIN}/initdb -D $PGDATA
  - sudo -u postgres ${PGBIN}/pg_ctl -D $PGDATA start

install:
  # Install dependencies.
  - composer install
  # Includes a version of DbUnit that is being kept compatible with PHPUnit.
  # The original DbUnit has been abandonned. https://github.com/sebastianbergmann/dbunit

  # Grant execute on scripts
  - chmod +x .travis/postgres_setup.sh

before_script:
  # Create database
  - psql -c 'create database indicia;' -U postgres -d postgres
  # Add extension for PostGIS
  - psql -U postgres -d indicia -c "create extension postgis"
  - psql -U postgres -d indicia -c "create extension postgis_topology"
  # Add extension for btree_gin indexes.
  - psql -U postgres -d indicia -c "create extension btree_gin"
  # Set up database.
  - .travis/postgres_setup.sh
  # Enable the phpunit module in config.php (meaning initialise() is not tested)
  - cp application/config/config.php.travis application/config/config.php
  # Provide a config file for the rest_api, spatial_index_builder and request_logging modules
  - cp modules/rest_api/config/rest.php.travis  modules/rest_api/config/rest.php
  - cp modules/spatial_index_builder/config/spatial_index_builder.php.travis  modules/spatial_index_builder/config/spatial_index_builder.php
  - cp modules/request_logging/config/request_logging.example.php modules/request_logging/config/request_logging.php

script:
  - vendor/phpunit/phpunit/phpunit --stderr --configuration phpunit-config-test.xml
  - vendor/phpunit/phpunit/phpunit --stderr --configuration phpunit-setup-check-test.xml
  - vendor/phpunit/phpunit/phpunit --stderr --configuration phpunit-home-test.xml
  # Repeat to upgrade modules
  - vendor/phpunit/phpunit/phpunit --stderr --configuration phpunit-home-test.xml
  - vendor/phpunit/phpunit/phpunit --stderr --configuration phpunit-tests.xml

after_script:
  - cat application/logs/*
