services:
    # A warehouse and postgresql container combined, as on Travis CI.
    warehouse:
        build: ./phpunit
        # Apache is configured to run on port 8080 in phpunit/Dockerfile  
        ports: 
            - "${PORT}:${PORT}"
        # Share the warehouse code between host and container
        volumes:
            - ..:/var/www/html/
